INSERT INTO survey_questions (question_text, category, weight)
VALUES
('I proactively schedule regular one-on-one meetings with each team member and protect that time from interruptions or cancellations.', 'CT', 1),
('When I spend time with team members, I am fully present-avoiding distractions like phones, email, or multitasking.', 'CT', 1),
('I adjust the frequency and depth of Caring Time based on individual team members'' preferences and needs.', 'CT', 1),
('I am available and attentive during moments when a team member is visibly stressed or in crisis, offering my undivided attention and support.', 'CT', 1),
('I prioritise Caring Time even during busy periods, managing my calendar and energy to consistently make time for my team.', 'CT', 1),
('I come to scheduled Caring Time prepared with meaningful agendas or topics that encourage open, supportive conversations beyond just status updates.', 'CT', 1),
('I balance Caring Time with empowering team members'' independence to avoid micromanagement or dependency.', 'CT', 1),
('I regularly use direct, face-to-face or video interactions for Caring Time rather than solely relying on email or quick check-ins.', 'CT', 1),
('I consciously protect Caring Time boundaries by limiting distractions and communicating availability clearly to my team and colleagues.', 'CT', 1),
('Over the past month, I have made consistent efforts to reach at least 6 hours of quality Caring Time per week for my team as research recommends.', 'CT', 1),
('I give my team members my full, undistracted attention during conversations.', 'RV', 1),
('I listen with the intent to understand-not just to respond or reply.', 'RV', 1),
('I ask open-ended and clarifying questions to deepen my understanding of team members'' perspectives.', 'RV', 1),
('I take notes during or immediately after conversations to capture key points and show respect.', 'RV', 1),
('I follow up with the team to close the communication loop on their ideas, feedback, or concerns.', 'RV', 1),
('I create safe spaces where team members feel comfortable sharing honest thoughts without fear of judgment.', 'RV', 1),
('I demonstrate genuine curiosity and a learning mindset during interactions with my team.', 'RV', 1),
('I actively recognise and validate the contributions and ideas shared by team members in team settings.', 'RV', 1),
('I schedule regular, protected one-on-one meetings specifically dedicated to listening and understanding team members.', 'RV', 1),
('I model vulnerability by sharing my own learning and invite two-way dialogue to build trust.', 'RV', 1),
('I proactively identify and remove obstacles that hinder my team''s performance.', 'AS', 1),
('I ensure my team has the right tools, technologies, and resources to succeed.', 'AS', 1),
('I provide clear role definitions, responsibilities, and expectations for every team member.', 'AS', 1),
('I give timely, constructive feedback focused on behaviours and growth-not blame.', 'AS', 1),
('I collaborate with team members to set actionable next steps for continuous improvement.', 'AS', 1),
('I invest in my team''s development by connecting them with training, mentorship, and growth opportunities.', 'AS', 1),
('I protect my team from unnecessary distractions, conflicting priorities, and organisational politics.', 'AS', 1),
('I balance support with empowering team members to take ownership and solve problems independently.', 'AS', 1),
('I regularly check in with my team to identify blockers and respond quickly with practical solutions.', 'AS', 1),
('I create a culture of continuous support and learning by modelling vulnerability and openness as a leader.', 'AS', 1),
('I deliver recognition that is specific and clearly tied to concrete actions or results rather than generic praise.', 'WR', 1),
('I focus recognition on contributions that exceed expectations, rather than routine or baseline performance.', 'WR', 1),
('I give timely recognition, aiming to acknowledge efforts as close to the event as possible to maximise impact.', 'WR', 1),
('I communicate the purpose and impact of the contribution clearly, helping team members understand why their effort matters.', 'WR', 1),
('I use a variety of recognition methods, including verbal praise, written thank-you notes, peer recognition, and public shout-outs.', 'WR', 1),
('I encourage and model peer-to-peer recognition within my team to build a culture of mutual appreciation.', 'WR', 1),
('I tailor my recognition approach to individual preferences and generational differences, balancing public and private forms.', 'WR', 1),
('I prepare ahead by noting meaningful contributions throughout projects so I can recognise them promptly and accurately.', 'WR', 1),
('I resist giving empty, excessive, or insincere praise that could dilute the impact and credibility of my recognition.', 'WR', 1),
('I recognise leaders above me as well as those I lead, understanding that upward recognition fosters alignment and motivation.', 'WR', 1),
('I foster an environment where team members feel safe to speak up, share ideas, and admit mistakes without fear of judgment or retaliation.', 'PT', 1),
('I demonstrate emotional courage by admitting my own uncertainties, limitations, and mistakes to model vulnerability.', 'PT', 1),
('I communicate openly and transparently, sharing information honestly and inviting dialogue rather than issuing directives.', 'PT', 1),
('I actively listen with empathy, practicing genuine presence and reflection to understand others'' feelings and perspectives.', 'PT', 1),
('I treat mistakes as learning opportunities and encourage a no-blame culture focused on growth and development.', 'PT', 1),
('I create clear, consistent expectations and promote shared responsibility, empowering the team to own challenges and solutions safely.', 'PT', 1),
('I adjust my communication style and support to match the unique personalities, needs, and contexts of individual team members (e.g., using DISC profiling).', 'PT', 1),
('I maintain calmness and emotional control, responding thoughtfully in tense situations to foster a steady, trusting team climate.', 'PT', 1),
('I invest in developing my emotional intelligence-regularly reflecting on my emotions, triggers, and social skills to improve leadership presence.', 'PT', 1),
('I proactively protect my team''s psychological well-being by recognising signs of stress or burnout and facilitating support or resources when needed.', 'PT', 1);
