spring.application.name=LeadershipCompass_CapstoneProjectBackend

spring.datasource.url=jdbc:postgresql://localhost:5432/leadershipCompass
spring.datasource.username=postgres
spring.datasource.password=leaderCompass26

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.modules.seed.enabled=true
app.modules.seed.path=classpath*:seed/modules/*.json

jwt.secret=ThisIsASecretKeyForLeadershipCompassJwtAuthenticationMustBeLongEnough
jwt.expiration=86400000